server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**


        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**


      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

#logging:
  #level:
    #org.springframework.cloud.gateway: DEBUG
    #com.ecom.api_gateway.Controller.filter: DEBUG  # or your actual package name

